name: Waze_Auto_Check_Nako3

on:
  workflow_dispatch:

jobs:
  run-nako3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nadesiko3
        run: npm install -g nadesiko3
      - name: Run Nadeshiko Script
        run: cnako3 check.nako3
        
